### ISSUE TITLE
os.date() argument corruption (solution included)

### ISSUE THREAD

**Issue by cbelyaev** [mlnlover11/KopiLua-v5.1.5#3]
Problem:
In the sample:
```
for i=1,10,1 do
  print(os.date("%H:%M:%S"))
end
```
time is printed in the first iteration only.

Solution:
file KopiLua/src/loslib.cs
line 153 must look like:
`CharPtr s = new CharPtr(LuaLOptString(L, 1, "%c"));`

**Comment by Dergard** [comment]
this is amazing!

**Comment by artymarty** [comment]
Thanks a lot! This weird one-off function was making me maad

**Comment by efrederickson** [comment]
This may fix one issue but does not fix the underlying problem that `strftime` is not implemented in this fork. I would recommend using one of the successive forks (such as NLua) which actually implements and fixes a lot more than just that issue.
